language: c++
dist: bionic
os: linux
services:
- docker
if: tag IS blank
jobs:
  include:
  - stage: Build Docker Image
    name: Build for Archlinux
    script: ./build-scripts/docker-build-and-release-archlinux.sh
  - stage: Build Binaries
    name: Build for ESP32
    script: ./build-scripts/docker-build-binary.sh
env:
  global:
  - DOCKER_USERNAME=cgspeck
  - secure: dKYSPqNG/3mq35FUUwoCCxoR3f05Gdf6UjGRUooQDrpfDwRDKwWK3LW1MffOH22wmF+s+jC9l7UQodNvb9a86HFnECz38FaCrWQYl6YhQeyBh9FT64zZIVngIVJ3Yi5/ts7NDi0Ja6TB+JvFxoBboClOZVXReFAQa70G5dk6sAWDdir2lEy/54yzNE0Ivws/RuYDWaLGT+728gnCXIfBZHJ8ZdzrQCYIzWAhWJtR7qUimppUIvg6S3rTOZSOhiG+14mDiMe45E69VSiHZWaqqkXqeB3RaK9V6pk+B7t4Uo1F0r9JXmfZMfaj/xz2AggYcFUcOJ1s/fX8Baj8Rtb9H87g2HfFlV5wHgp8e9V+8Dho6CIrPp4LBlq091QzpZmOEiwsI4C7Za4PskRj48UUjNBrFw3Idpyi+S0n7bYrWiaEhvZm1XZlGbCr+acW3WOzAKSWIuNvuA5QJ8ygWZ3fFk32MaAZavh7V2WmFsmS2Bg9lBujyNCElw8Klkrs9On5pijARZZJKuuQ07Wn8US0OdNsuRdq+JRSDFLcJSAz6xidmSiaeZ7KmkLA6/pWLLTdL6zMJbrx1BYZads3u7HN35JBpTqGRrqlZR5lk7/Yybiw7/udhx9kz8kxJulJxbdU1Ul1AIh73fHqMIhSFSHkTK+zu14GIA1Pf7Fut8gUI7s=
